#!/bin/env bash

if command -v sha256sum &> /dev/null; then
    SHA_CMD="sha256sum"
elif command -v shasum &> /dev/null; then
    SHA_CMD="shasum -a 256" # macOS
else
    echo "Error: sha256sum or shasum weren't found. Hashes can't be updated."
    exit 1
fi

for DATASET_ARCHIVE in $(git diff --name-only --staged -- '*.zip'); do
	ARCHIVE_FILES=$(zipinfo -1 "$DATASET_ARCHIVE")
	ARCHIVE_CONTENTS_FILE="${DATASET_ARCHIVE%.zip}.txt"
	echo "$ARCHIVE_FILES" | sort >"$ARCHIVE_CONTENTS_FILE"
	git add "$ARCHIVE_CONTENTS_FILE"

	HASH_FILE="${DATASET_ARCHIVE%.zip}.sha256"
	NEW_HASH=$($SHA_CMD "$DATASET_ARCHIVE" | awk '{print $1}')
	echo -n "$NEW_HASH" > "$HASH_FILE"
	git add "$HASH_FILE"
done
